spring.application.name=spring-boot-4-x-fw-7-x
spring.mvc.apiversion.use.header=false
spring.mvc.apiversion.use.param=true
spring.mvc.apiversion.param-name=api-version

spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.queues=orders.events
spring.jms.template.default-destination=orders.events
